# https://wiki.hypr.land/Configuring/


$launcher = pkill wofi || wofi --normal-window --show drun --allow-images
$terminal = kitty


#############################
### ENVIRONMENT VARIABLES ###
#############################

# See https://wiki.hypr.land/Configuring/Environment-variables/

env = XCURSOR_SIZE,24
env = HYPRCURSOR_SIZE,24

# QT
env = QT_QPA_PLATFORM,wayland;xcb
env = QT_QPA_PLATFORMTHEME,qt6ct
env = QT_WAYLAND_DISABLE_WINDOWDECORATION,1
env = QT_AUTO_SCREEN_SCALE_FACTOR,1
env = QT_STYLE_OVERRIDE,kvantum

# Toolkit Backend Variables
env = GDK_BACKEND,wayland,x11,*
env = SDL_VIDEODRIVER,wayland
env = CLUTTER_BACKEND,wayland

# XDG Specifications
env = XDG_CURRENT_DESKTOP,Hyprland
env = XDG_SESSION_TYPE,wayland
env = XDG_SESSION_DESKTOP,Hyprland


##############################
### WINDOWS AND WORKSPACES ###
##############################

# https://wiki.hypr.land/Configuring/Window-Rules/
# https://wiki.hypr.land/Configuring/Workspace-Rules/

# Ignore maximize requests from apps. You'll probably like this.
windowrule = suppressevent maximize, class:.*

# Fix some dragging issues with XWayland
windowrule = nofocus,class:^$,title:^$,xwayland:1,floating:1,fullscreen:0,pinned:0


###############
### SOURCES ###
###############

source = ~/.config/hypr/monitors.conf

source = ~/.config/hypr/hyprland/input.conf

source = ~/.config/hypr/hyprland/binds-and-gestures.conf

source = ~/.config/hypr/hyprland/autostart.conf
source = ~/.config/hypr/hyprland/look-and-feel.conf
