exec-once = nm-applet --indicator
exec-once = wpaperd
exec-once = mako
exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store
exec-once = ~/.config/wpaperd/wallhaven.sh
