# ONLY INITIAL CONF
# THIS FILE WILL BE OVERWRITTEN BY
# ~/.config/hygge/tera/home/.config/hypr/hyprland/look-and-feel.conf.tera

animations {
  enabled = yes, please :)
}

misc {
  disable_hyprland_logo = true
  vrr = 1
}
